WARNING:tensorflow:From /home/pierre/miniconda3/envs/teachDRL/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:206: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.random.categorical` instead.
Traceback (most recent call last):
  File "run_mazes.py", line 127, in <module>
    path_gif = path_gif, path_sampled_maze=path_sampled_maze, path_metrics=path_metrics, path_maze_visu=path_maze_visu, gpu_name=gpu_name)
  File "/home/pierre/Git/teachDeepRL/teachDRL/spinup/algos/ppo/ppo.py", line 225, in ppo
    var_counts = tuple(core.count_vars(scope) for scope in ['pi', 'v'])
  File "/home/pierre/Git/teachDeepRL/teachDRL/spinup/algos/ppo/ppo.py", line 225, in <genexpr>
    var_counts = tuple(core.count_vars(scope) for scope in ['pi', 'v'])
  File "/home/pierre/Git/teachDeepRL/teachDRL/spinup/algos/ppo/core.py", line 51, in count_vars
    v = get_vars(scope)
  File "/home/pierre/Git/teachDeepRL/teachDRL/spinup/algos/ppo/core.py", line 48, in get_vars
    return [x for x in tf.trainable_variables() if scope in x.name]
AttributeError: module 'tensorflow' has no attribute 'trainable_variables'